version: '3'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_DATABASE_TYPE=postgres
      - GF_DATABASE_HOST=${{ secrets.PGHOST }}
      - GF_DATABASE_NAME=${{ secrets.PGDATABASE }}
      - GF_DATABASE_USER=${{ secrets.PGUSER }}
      - GF_DATABASE_PASSWORD=${{ secrets.PGPASSWORD }}
      - GF_DATABASE_SSL_MODE=disable
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-plugins:/var/lib/grafana/plugins

volumes:
  grafana-data:
  grafana-plugins: